/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowLogin (void)
{
  GtkWidget *windowLogin;
  GtkWidget *fixed2;
  GtkWidget *entryLoginI;
  GtkWidget *entryPasswordI;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *buttonCreerCompte;
  GtkWidget *buttonAuthentification;
  GtkWidget *labelResultatI;

  windowLogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowLogin), _("Login"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowLogin), fixed2);

  entryLoginI = gtk_entry_new ();
  gtk_widget_show (entryLoginI);
  gtk_fixed_put (GTK_FIXED (fixed2), entryLoginI, 208, 48);
  gtk_widget_set_size_request (entryLoginI, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLoginI), 8226);

  entryPasswordI = gtk_entry_new ();
  gtk_widget_show (entryPasswordI);
  gtk_fixed_put (GTK_FIXED (fixed2), entryPasswordI, 208, 120);
  gtk_widget_set_size_request (entryPasswordI, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPasswordI), 8226);

  label7 = gtk_label_new (_("Login auatilisateur "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 24, 48);
  gtk_widget_set_size_request (label7, 144, 41);

  label8 = gtk_label_new (_("Mot de Passe"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 8, 120);
  gtk_widget_set_size_request (label8, 160, 33);

  buttonCreerCompte = gtk_button_new_with_mnemonic (_("Creer un compte"));
  gtk_widget_show (buttonCreerCompte);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonCreerCompte, 264, 192);
  gtk_widget_set_size_request (buttonCreerCompte, 232, 37);

  buttonAuthentification = gtk_button_new_with_mnemonic (_("S'authentifier"));
  gtk_widget_show (buttonAuthentification);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAuthentification, 80, 200);
  gtk_widget_set_size_request (buttonAuthentification, 114, 32);

  labelResultatI = gtk_label_new ("");
  gtk_widget_show (labelResultatI);
  gtk_fixed_put (GTK_FIXED (fixed2), labelResultatI, 112, 376);
  gtk_widget_set_size_request (labelResultatI, 288, 65);

  g_signal_connect ((gpointer) buttonCreerCompte, "clicked",
                    G_CALLBACK (on_buttonCreerCompte_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAuthentification, "clicked",
                    G_CALLBACK (on_buttonAuthentification_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowLogin, windowLogin, "windowLogin");
  GLADE_HOOKUP_OBJECT (windowLogin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowLogin, entryLoginI, "entryLoginI");
  GLADE_HOOKUP_OBJECT (windowLogin, entryPasswordI, "entryPasswordI");
  GLADE_HOOKUP_OBJECT (windowLogin, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowLogin, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowLogin, buttonCreerCompte, "buttonCreerCompte");
  GLADE_HOOKUP_OBJECT (windowLogin, buttonAuthentification, "buttonAuthentification");
  GLADE_HOOKUP_OBJECT (windowLogin, labelResultatI, "labelResultatI");

  return windowLogin;
}

GtkWidget*
create_windowInscription (void)
{
  GtkWidget *windowInscription;
  GtkWidget *fixed1;
  GtkWidget *entryNomL;
  GtkWidget *labelNomUtilisateur;
  GtkWidget *entryLoginL;
  GtkWidget *labelLoginUtilisateur;
  GtkWidget *labelMPUtilisateur;
  GtkWidget *entryPasswordL;
  GtkWidget *labelRoleUtilisateur;
  GtkWidget *buttonLoginInscrire;
  GtkWidget *buttonInscription;
  GtkWidget *labelResultatUtilisateurL;
  GtkWidget *radioRoleAdminL;
  GSList *radioRoleAdminL_group = NULL;
  GtkWidget *radioRoleUserL;

  windowInscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowInscription), _("Inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowInscription), fixed1);

  entryNomL = gtk_entry_new ();
  gtk_widget_show (entryNomL);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNomL, 184, 56);
  gtk_widget_set_size_request (entryNomL, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomL), 8226);

  labelNomUtilisateur = gtk_label_new (_("Nom Utilisateur :"));
  gtk_widget_show (labelNomUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNomUtilisateur, 24, 56);
  gtk_widget_set_size_request (labelNomUtilisateur, 128, 32);

  entryLoginL = gtk_entry_new ();
  gtk_widget_show (entryLoginL);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLoginL, 184, 120);
  gtk_widget_set_size_request (entryLoginL, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLoginL), 8226);

  labelLoginUtilisateur = gtk_label_new (_("Login auatilisateur "));
  gtk_widget_show (labelLoginUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelLoginUtilisateur, 16, 120);
  gtk_widget_set_size_request (labelLoginUtilisateur, 144, 41);

  labelMPUtilisateur = gtk_label_new (_("Mot de Passe"));
  gtk_widget_show (labelMPUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMPUtilisateur, 0, 184);
  gtk_widget_set_size_request (labelMPUtilisateur, 160, 33);

  entryPasswordL = gtk_entry_new ();
  gtk_widget_show (entryPasswordL);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPasswordL, 184, 176);
  gtk_widget_set_size_request (entryPasswordL, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPasswordL), 8226);

  labelRoleUtilisateur = gtk_label_new (_("Role Utilisateur "));
  gtk_widget_show (labelRoleUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelRoleUtilisateur, 16, 240);
  gtk_widget_set_size_request (labelRoleUtilisateur, 112, 41);

  buttonLoginInscrire = gtk_button_new_with_mnemonic (_("J'ai un compte deja"));
  gtk_widget_show (buttonLoginInscrire);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonLoginInscrire, 272, 320);
  gtk_widget_set_size_request (buttonLoginInscrire, 256, 40);

  buttonInscription = gtk_button_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (buttonInscription);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonInscription, 80, 320);
  gtk_widget_set_size_request (buttonInscription, 136, 37);

  labelResultatUtilisateurL = gtk_label_new ("");
  gtk_widget_show (labelResultatUtilisateurL);
  gtk_fixed_put (GTK_FIXED (fixed1), labelResultatUtilisateurL, 112, 376);
  gtk_widget_set_size_request (labelResultatUtilisateurL, 288, 65);

  radioRoleAdminL = gtk_radio_button_new_with_mnemonic (NULL, _("Administrateur"));
  gtk_widget_show (radioRoleAdminL);
  gtk_fixed_put (GTK_FIXED (fixed1), radioRoleAdminL, 176, 256);
  gtk_widget_set_size_request (radioRoleAdminL, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioRoleAdminL), radioRoleAdminL_group);
  radioRoleAdminL_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioRoleAdminL));

  radioRoleUserL = gtk_radio_button_new_with_mnemonic (NULL, _("Agent"));
  gtk_widget_show (radioRoleUserL);
  gtk_fixed_put (GTK_FIXED (fixed1), radioRoleUserL, 336, 256);
  gtk_widget_set_size_request (radioRoleUserL, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioRoleUserL), radioRoleAdminL_group);
  radioRoleAdminL_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioRoleUserL));

  g_signal_connect ((gpointer) buttonLoginInscrire, "clicked",
                    G_CALLBACK (on_buttonLoginInscrire_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonInscription, "clicked",
                    G_CALLBACK (on_buttonInscription_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowInscription, windowInscription, "windowInscription");
  GLADE_HOOKUP_OBJECT (windowInscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowInscription, entryNomL, "entryNomL");
  GLADE_HOOKUP_OBJECT (windowInscription, labelNomUtilisateur, "labelNomUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, entryLoginL, "entryLoginL");
  GLADE_HOOKUP_OBJECT (windowInscription, labelLoginUtilisateur, "labelLoginUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, labelMPUtilisateur, "labelMPUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, entryPasswordL, "entryPasswordL");
  GLADE_HOOKUP_OBJECT (windowInscription, labelRoleUtilisateur, "labelRoleUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, buttonLoginInscrire, "buttonLoginInscrire");
  GLADE_HOOKUP_OBJECT (windowInscription, buttonInscription, "buttonInscription");
  GLADE_HOOKUP_OBJECT (windowInscription, labelResultatUtilisateurL, "labelResultatUtilisateurL");
  GLADE_HOOKUP_OBJECT (windowInscription, radioRoleAdminL, "radioRoleAdminL");
  GLADE_HOOKUP_OBJECT (windowInscription, radioRoleUserL, "radioRoleUserL");

  return windowInscription;
}

GtkWidget*
create_windowMenu (void)
{
  GtkWidget *windowMenu;
  GtkWidget *fixed3;
  GtkWidget *buttonGestionParkihg;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *label9;
  GtkWidget *buttonGestionReservation;
  GtkWidget *buttonGestionService;
  GtkWidget *buttonGestionAgent;
  GtkWidget *buttonGestionCitoyen;
  GtkWidget *buttonGestionReclamation;
  GtkWidget *buttonQuitterMenu;

  windowMenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowMenu), _("Menu"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowMenu), fixed3);

  buttonGestionParkihg = gtk_button_new ();
  gtk_widget_show (buttonGestionParkihg);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionParkihg, 136, 88);
  gtk_widget_set_size_request (buttonGestionParkihg, 296, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonGestionParkihg), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  label9 = gtk_label_new_with_mnemonic (_("Gestion des Parkings"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox1), label9, FALSE, FALSE, 0);

  buttonGestionReservation = gtk_button_new_with_mnemonic (_("Gestion des Reservations"));
  gtk_widget_show (buttonGestionReservation);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionReservation, 136, 144);
  gtk_widget_set_size_request (buttonGestionReservation, 296, 48);

  buttonGestionService = gtk_button_new_with_mnemonic (_("Gestion des Services"));
  gtk_widget_show (buttonGestionService);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionService, 136, 208);
  gtk_widget_set_size_request (buttonGestionService, 296, 48);

  buttonGestionAgent = gtk_button_new_with_mnemonic (_("Gestion des Agents"));
  gtk_widget_show (buttonGestionAgent);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionAgent, 136, 272);
  gtk_widget_set_size_request (buttonGestionAgent, 296, 45);

  buttonGestionCitoyen = gtk_button_new_with_mnemonic (_("Gestion des Citoyens"));
  gtk_widget_show (buttonGestionCitoyen);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionCitoyen, 136, 336);
  gtk_widget_set_size_request (buttonGestionCitoyen, 296, 45);

  buttonGestionReclamation = gtk_button_new_with_mnemonic (_("Gestion des Reclamations"));
  gtk_widget_show (buttonGestionReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionReclamation, 136, 392);
  gtk_widget_set_size_request (buttonGestionReclamation, 296, 48);

  buttonQuitterMenu = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (buttonQuitterMenu);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonQuitterMenu, 136, 456);
  gtk_widget_set_size_request (buttonQuitterMenu, 288, 48);

  g_signal_connect ((gpointer) buttonGestionParkihg, "clicked",
                    G_CALLBACK (on_buttonGestionParkihg_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionReservation, "clicked",
                    G_CALLBACK (on_buttonGestionReservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionService, "clicked",
                    G_CALLBACK (on_buttonGestionService_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionAgent, "clicked",
                    G_CALLBACK (on_buttonGestionAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionCitoyen, "clicked",
                    G_CALLBACK (on_buttonGestionCitoyen_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionReclamation, "clicked",
                    G_CALLBACK (on_buttonGestionReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonQuitterMenu, "clicked",
                    G_CALLBACK (on_buttonQuitterMenu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowMenu, windowMenu, "windowMenu");
  GLADE_HOOKUP_OBJECT (windowMenu, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionParkihg, "buttonGestionParkihg");
  GLADE_HOOKUP_OBJECT (windowMenu, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowMenu, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowMenu, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionReservation, "buttonGestionReservation");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionService, "buttonGestionService");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionAgent, "buttonGestionAgent");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionCitoyen, "buttonGestionCitoyen");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionReclamation, "buttonGestionReclamation");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonQuitterMenu, "buttonQuitterMenu");

  return windowMenu;
}

GtkWidget*
create_windowGestionParking (void)
{
  GtkWidget *windowGestionParking;

  windowGestionParking = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionParking), _("Gestion des Parkings"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionParking, windowGestionParking, "windowGestionParking");

  return windowGestionParking;
}

GtkWidget*
create_windowGestionReservation (void)
{
  GtkWidget *windowGestionReservation;

  windowGestionReservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionReservation), _("Gestion des Reservations"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionReservation, windowGestionReservation, "windowGestionReservation");

  return windowGestionReservation;
}

GtkWidget*
create_windowGestionCitoyen (void)
{
  GtkWidget *windowGestionCitoyen;

  windowGestionCitoyen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionCitoyen), _("Gestion des Citoyens"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionCitoyen, windowGestionCitoyen, "windowGestionCitoyen");

  return windowGestionCitoyen;
}

GtkWidget*
create_windowGestionService (void)
{
  GtkWidget *windowGestionService;

  windowGestionService = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionService), _("Gestion des Services"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionService, windowGestionService, "windowGestionService");

  return windowGestionService;
}

GtkWidget*
create_windowGestionAgent (void)
{
  GtkWidget *windowGestionAgent;

  windowGestionAgent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionAgent), _("Gestion des Agents"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionAgent, windowGestionAgent, "windowGestionAgent");

  return windowGestionAgent;
}

GtkWidget*
create_windowGestionReclamation (void)
{
  GtkWidget *windowGestionReclamation;

  windowGestionReclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionReclamation), _("Gestion des Reclamations"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionReclamation, windowGestionReclamation, "windowGestionReclamation");

  return windowGestionReclamation;
}

