/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowLogin (void)
{
  GtkWidget *windowLogin;
  GtkWidget *fixed2;
  GtkWidget *entryLoginI;
  GtkWidget *entryPasswordI;
  GtkWidget *label8;
  GtkWidget *labelResultatI;
  GtkWidget *buttonAuthentification;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image15;
  GtkWidget *label46;
  GtkWidget *buttonCreerCompte;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image16;
  GtkWidget *label47;
  GtkWidget *label7;

  windowLogin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowLogin), _("Login"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowLogin), fixed2);

  entryLoginI = gtk_entry_new ();
  gtk_widget_show (entryLoginI);
  gtk_fixed_put (GTK_FIXED (fixed2), entryLoginI, 208, 48);
  gtk_widget_set_size_request (entryLoginI, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLoginI), 8226);

  entryPasswordI = gtk_entry_new ();
  gtk_widget_show (entryPasswordI);
  gtk_fixed_put (GTK_FIXED (fixed2), entryPasswordI, 208, 120);
  gtk_widget_set_size_request (entryPasswordI, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPasswordI), 8226);

  label8 = gtk_label_new (_("Mot de Passe"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 8, 120);
  gtk_widget_set_size_request (label8, 160, 33);

  labelResultatI = gtk_label_new ("");
  gtk_widget_show (labelResultatI);
  gtk_fixed_put (GTK_FIXED (fixed2), labelResultatI, 112, 376);
  gtk_widget_set_size_request (labelResultatI, 288, 65);

  buttonAuthentification = gtk_button_new ();
  gtk_widget_show (buttonAuthentification);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAuthentification, 40, 192);
  gtk_widget_set_size_request (buttonAuthentification, 168, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonAuthentification), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox16), image15, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("S'authentifier"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox16), label46, FALSE, FALSE, 0);

  buttonCreerCompte = gtk_button_new ();
  gtk_widget_show (buttonCreerCompte);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonCreerCompte, 232, 192);
  gtk_widget_set_size_request (buttonCreerCompte, 232, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonCreerCompte), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image16 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox17), image16, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Creer un compte"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox17), label47, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("Login  "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 24, 48);
  gtk_widget_set_size_request (label7, 144, 41);

  g_signal_connect ((gpointer) buttonAuthentification, "clicked",
                    G_CALLBACK (on_buttonAuthentification_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonCreerCompte, "clicked",
                    G_CALLBACK (on_buttonCreerCompte_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowLogin, windowLogin, "windowLogin");
  GLADE_HOOKUP_OBJECT (windowLogin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowLogin, entryLoginI, "entryLoginI");
  GLADE_HOOKUP_OBJECT (windowLogin, entryPasswordI, "entryPasswordI");
  GLADE_HOOKUP_OBJECT (windowLogin, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowLogin, labelResultatI, "labelResultatI");
  GLADE_HOOKUP_OBJECT (windowLogin, buttonAuthentification, "buttonAuthentification");
  GLADE_HOOKUP_OBJECT (windowLogin, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (windowLogin, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (windowLogin, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowLogin, label46, "label46");
  GLADE_HOOKUP_OBJECT (windowLogin, buttonCreerCompte, "buttonCreerCompte");
  GLADE_HOOKUP_OBJECT (windowLogin, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (windowLogin, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (windowLogin, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowLogin, label47, "label47");
  GLADE_HOOKUP_OBJECT (windowLogin, label7, "label7");

  return windowLogin;
}

GtkWidget*
create_windowInscription (void)
{
  GtkWidget *windowInscription;
  GtkWidget *fixed1;
  GtkWidget *entryNomL;
  GtkWidget *entryLoginL;
  GtkWidget *entryPasswordL;
  GtkWidget *buttonInscription;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image17;
  GtkWidget *label48;
  GtkWidget *buttonLoginInscrire;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image18;
  GtkWidget *label49;
  GtkWidget *labelResultatUtilisateurL;
  GtkWidget *radioRoleAdminL;
  GSList *radioRoleAdminL_group = NULL;
  GtkWidget *radioRoleUserL;
  GtkWidget *labelNomUtilisateur;
  GtkWidget *labelLoginUtilisateur;
  GtkWidget *labelMPUtilisateur;
  GtkWidget *labelRoleUtilisateur;

  windowInscription = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowInscription), _("Inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowInscription), fixed1);

  entryNomL = gtk_entry_new ();
  gtk_widget_show (entryNomL);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNomL, 184, 56);
  gtk_widget_set_size_request (entryNomL, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomL), 8226);

  entryLoginL = gtk_entry_new ();
  gtk_widget_show (entryLoginL);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLoginL, 184, 120);
  gtk_widget_set_size_request (entryLoginL, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLoginL), 8226);

  entryPasswordL = gtk_entry_new ();
  gtk_widget_show (entryPasswordL);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPasswordL, 184, 176);
  gtk_widget_set_size_request (entryPasswordL, 184, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPasswordL), 8226);

  buttonInscription = gtk_button_new ();
  gtk_widget_show (buttonInscription);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonInscription, 80, 320);
  gtk_widget_set_size_request (buttonInscription, 136, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonInscription), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox18), image17, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox18), label48, FALSE, FALSE, 0);

  buttonLoginInscrire = gtk_button_new ();
  gtk_widget_show (buttonLoginInscrire);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonLoginInscrire, 248, 320);
  gtk_widget_set_size_request (buttonLoginInscrire, 256, 40);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonLoginInscrire), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image18 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox19), image18, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("J'ai un compte deja"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox19), label49, FALSE, FALSE, 0);

  labelResultatUtilisateurL = gtk_label_new ("");
  gtk_widget_show (labelResultatUtilisateurL);
  gtk_fixed_put (GTK_FIXED (fixed1), labelResultatUtilisateurL, 112, 376);
  gtk_widget_set_size_request (labelResultatUtilisateurL, 288, 65);

  radioRoleAdminL = gtk_radio_button_new_with_mnemonic (NULL, _("Administrateur"));
  gtk_widget_show (radioRoleAdminL);
  gtk_fixed_put (GTK_FIXED (fixed1), radioRoleAdminL, 176, 256);
  gtk_widget_set_size_request (radioRoleAdminL, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioRoleAdminL), radioRoleAdminL_group);
  radioRoleAdminL_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioRoleAdminL));

  radioRoleUserL = gtk_radio_button_new_with_mnemonic (NULL, _("Citoyen"));
  gtk_widget_show (radioRoleUserL);
  gtk_fixed_put (GTK_FIXED (fixed1), radioRoleUserL, 336, 256);
  gtk_widget_set_size_request (radioRoleUserL, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioRoleUserL), radioRoleAdminL_group);
  radioRoleAdminL_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioRoleUserL));

  labelNomUtilisateur = gtk_label_new (_("Nom Utilisateur :"));
  gtk_widget_show (labelNomUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelNomUtilisateur, 24, 56);
  gtk_widget_set_size_request (labelNomUtilisateur, 128, 32);

  labelLoginUtilisateur = gtk_label_new (_("Login "));
  gtk_widget_show (labelLoginUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelLoginUtilisateur, 16, 120);
  gtk_widget_set_size_request (labelLoginUtilisateur, 144, 41);

  labelMPUtilisateur = gtk_label_new (_("Mot de Passe"));
  gtk_widget_show (labelMPUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelMPUtilisateur, 0, 184);
  gtk_widget_set_size_request (labelMPUtilisateur, 160, 33);

  labelRoleUtilisateur = gtk_label_new (_("Role"));
  gtk_widget_show (labelRoleUtilisateur);
  gtk_fixed_put (GTK_FIXED (fixed1), labelRoleUtilisateur, 16, 240);
  gtk_widget_set_size_request (labelRoleUtilisateur, 112, 41);

  g_signal_connect ((gpointer) buttonInscription, "clicked",
                    G_CALLBACK (on_buttonInscription_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonLoginInscrire, "clicked",
                    G_CALLBACK (on_buttonLoginInscrire_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowInscription, windowInscription, "windowInscription");
  GLADE_HOOKUP_OBJECT (windowInscription, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowInscription, entryNomL, "entryNomL");
  GLADE_HOOKUP_OBJECT (windowInscription, entryLoginL, "entryLoginL");
  GLADE_HOOKUP_OBJECT (windowInscription, entryPasswordL, "entryPasswordL");
  GLADE_HOOKUP_OBJECT (windowInscription, buttonInscription, "buttonInscription");
  GLADE_HOOKUP_OBJECT (windowInscription, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (windowInscription, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (windowInscription, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowInscription, label48, "label48");
  GLADE_HOOKUP_OBJECT (windowInscription, buttonLoginInscrire, "buttonLoginInscrire");
  GLADE_HOOKUP_OBJECT (windowInscription, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (windowInscription, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (windowInscription, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowInscription, label49, "label49");
  GLADE_HOOKUP_OBJECT (windowInscription, labelResultatUtilisateurL, "labelResultatUtilisateurL");
  GLADE_HOOKUP_OBJECT (windowInscription, radioRoleAdminL, "radioRoleAdminL");
  GLADE_HOOKUP_OBJECT (windowInscription, radioRoleUserL, "radioRoleUserL");
  GLADE_HOOKUP_OBJECT (windowInscription, labelNomUtilisateur, "labelNomUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, labelLoginUtilisateur, "labelLoginUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, labelMPUtilisateur, "labelMPUtilisateur");
  GLADE_HOOKUP_OBJECT (windowInscription, labelRoleUtilisateur, "labelRoleUtilisateur");

  return windowInscription;
}

GtkWidget*
create_windowMenu (void)
{
  GtkWidget *windowMenu;
  GtkWidget *fixed3;
  GtkWidget *buttonGestionParkihg;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *label9;
  GtkWidget *buttonGestionReservation;
  GtkWidget *buttonGestionService;
  GtkWidget *buttonGestionAgent;
  GtkWidget *buttonGestionCitoyen;
  GtkWidget *buttonGestionReclamation;
  GtkWidget *buttonQuitterMenu;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image19;
  GtkWidget *label50;

  windowMenu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowMenu), _("Menu"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowMenu), fixed3);

  buttonGestionParkihg = gtk_button_new ();
  gtk_widget_show (buttonGestionParkihg);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionParkihg, 136, 88);
  gtk_widget_set_size_request (buttonGestionParkihg, 296, 48);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonGestionParkihg), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  label9 = gtk_label_new_with_mnemonic (_("Gestion des Parkings"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox1), label9, FALSE, FALSE, 0);

  buttonGestionReservation = gtk_button_new_with_mnemonic (_("Gestion des Reservations"));
  gtk_widget_show (buttonGestionReservation);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionReservation, 136, 144);
  gtk_widget_set_size_request (buttonGestionReservation, 296, 48);

  buttonGestionService = gtk_button_new_with_mnemonic (_("Gestion des Services"));
  gtk_widget_show (buttonGestionService);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionService, 136, 208);
  gtk_widget_set_size_request (buttonGestionService, 296, 48);

  buttonGestionAgent = gtk_button_new_with_mnemonic (_("Gestion des Agents"));
  gtk_widget_show (buttonGestionAgent);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionAgent, 136, 272);
  gtk_widget_set_size_request (buttonGestionAgent, 296, 45);

  buttonGestionCitoyen = gtk_button_new_with_mnemonic (_("Gestion des Citoyens"));
  gtk_widget_show (buttonGestionCitoyen);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionCitoyen, 136, 336);
  gtk_widget_set_size_request (buttonGestionCitoyen, 296, 45);

  buttonGestionReclamation = gtk_button_new_with_mnemonic (_("Gestion des Reclamations"));
  gtk_widget_show (buttonGestionReclamation);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonGestionReclamation, 136, 392);
  gtk_widget_set_size_request (buttonGestionReclamation, 296, 48);

  buttonQuitterMenu = gtk_button_new ();
  gtk_widget_show (buttonQuitterMenu);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonQuitterMenu, 136, 456);
  gtk_widget_set_size_request (buttonQuitterMenu, 288, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonQuitterMenu), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image19 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox20), image19, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox20), label50, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonGestionParkihg, "clicked",
                    G_CALLBACK (on_buttonGestionParkihg_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionReservation, "clicked",
                    G_CALLBACK (on_buttonGestionReservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionService, "clicked",
                    G_CALLBACK (on_buttonGestionService_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionAgent, "clicked",
                    G_CALLBACK (on_buttonGestionAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionCitoyen, "clicked",
                    G_CALLBACK (on_buttonGestionCitoyen_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonGestionReclamation, "clicked",
                    G_CALLBACK (on_buttonGestionReclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonQuitterMenu, "clicked",
                    G_CALLBACK (on_buttonQuitterMenu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowMenu, windowMenu, "windowMenu");
  GLADE_HOOKUP_OBJECT (windowMenu, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionParkihg, "buttonGestionParkihg");
  GLADE_HOOKUP_OBJECT (windowMenu, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowMenu, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowMenu, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionReservation, "buttonGestionReservation");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionService, "buttonGestionService");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionAgent, "buttonGestionAgent");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionCitoyen, "buttonGestionCitoyen");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonGestionReclamation, "buttonGestionReclamation");
  GLADE_HOOKUP_OBJECT (windowMenu, buttonQuitterMenu, "buttonQuitterMenu");
  GLADE_HOOKUP_OBJECT (windowMenu, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (windowMenu, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (windowMenu, image19, "image19");
  GLADE_HOOKUP_OBJECT (windowMenu, label50, "label50");

  return windowMenu;
}

GtkWidget*
create_windowGestionParking (void)
{
  GtkWidget *windowGestionParking;
  GtkWidget *notebook1;
  GtkWidget *fixed8;
  GtkWidget *labelNumeroPJ;
  GtkObject *spinNumeroPJ_adj;
  GtkWidget *spinNumeroPJ;
  GtkWidget *labelDatePJ;
  GtkObject *spinJourPJ_adj;
  GtkWidget *spinJourPJ;
  GtkObject *spinMoisPJ_adj;
  GtkWidget *spinMoisPJ;
  GtkObject *spinAnneePJ_adj;
  GtkWidget *spinAnneePJ;
  GtkWidget *labelAnneePJ;
  GtkObject *spinCapacitePJ_adj;
  GtkWidget *spinCapacitePJ;
  GtkWidget *entryNomPJ;
  GtkWidget *labelAdressePJ;
  GtkWidget *entryAdressePJ;
  GtkWidget *entryPrixPJ;
  GtkWidget *labelSecurite;
  GtkWidget *labelNomPJ;
  GtkWidget *labelPrixPJ;
  GtkWidget *labelSecteurPJ;
  GtkWidget *buttonAjouterParking;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label18;
  GtkWidget *checkSecuritePJ1;
  GtkWidget *checkSecuritePJ2;
  GtkWidget *radioSecteurPJ1;
  GSList *radioSecteurPJ1_group = NULL;
  GtkWidget *radioSecteurPJ2;
  GtkWidget *labelResultatPJ;
  GtkWidget *buttonMenuPJ;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image2;
  GtkWidget *label19;
  GtkWidget *labelGAjouterParking;
  GtkWidget *fixed9;
  GtkObject *spinNumeroPM_adj;
  GtkWidget *spinNumeroPM;
  GtkObject *spinJourPM_adj;
  GtkWidget *spinJourPM;
  GtkObject *spinMoisPM_adj;
  GtkWidget *spinMoisPM;
  GtkObject *spinAnneePM_adj;
  GtkWidget *spinAnneePM;
  GtkObject *spinCapacitePM_adj;
  GtkWidget *spinCapacitePM;
  GtkWidget *entryNomPM;
  GtkWidget *entryAdressePM;
  GtkWidget *entryPrixPM;
  GtkWidget *labelNomPM;
  GtkWidget *labelDatePM;
  GtkWidget *labelAdressePM;
  GtkWidget *labelPrixPM;
  GtkWidget *labelCapacitePM;
  GtkWidget *labelSecuritePM;
  GtkWidget *labelSecteurPM;
  GtkWidget *buttonModifierParking;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image5;
  GtkWidget *label31;
  GtkWidget *buttonRecupererPM;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image6;
  GtkWidget *label32;
  GtkWidget *checkSecuritePM1;
  GtkWidget *checkSecuritePM2;
  GtkWidget *radioSecteurPM1;
  GSList *radioSecteurPM1_group = NULL;
  GtkWidget *radioSecteurPM2;
  GtkWidget *labelResultatPM;
  GtkWidget *buttonMenuPM;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image4;
  GtkWidget *label30;
  GtkWidget *labelNumeroPM;
  GtkWidget *labelGModifierParking;
  GtkWidget *fixed6;
  GtkWidget *treeview1;
  GtkWidget *buttonMenuPCH;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image10;
  GtkWidget *label36;
  GtkWidget *buttonParkingTrier;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image9;
  GtkWidget *label35;
  GtkWidget *buttonParkingAvecAgent;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image7;
  GtkWidget *label33;
  GtkWidget *buttonParkingSansAgent;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image8;
  GtkWidget *label34;
  GtkWidget *labelGChercherParking;
  GtkWidget *fixed7;
  GtkWidget *labelParkingPS;
  GtkWidget *labelResultatSP;
  GtkWidget *comboboxParkingPS;
  GtkWidget *buttonActualiserLPS;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image11;
  GtkWidget *label42;
  GtkWidget *buttonSupprimerPS;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image12;
  GtkWidget *label43;
  GtkWidget *labelGSupprimerParking;
  GtkWidget *fixed4;
  GtkWidget *treeview2;
  GtkWidget *labelParkingLAffAg;
  GtkWidget *labelAgentLAffAg;
  GtkWidget *comboboxParkingLAffAg;
  GtkWidget *comboboxAgentLAffAg;
  GtkWidget *labelResultatAffAg;
  GtkWidget *buttonActualiserAffAg;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image13;
  GtkWidget *label44;
  GtkWidget *buttonAffecterAgent;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image14;
  GtkWidget *label45;
  GtkWidget *labelGAffecterAgent;

  windowGestionParking = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionParking), _("Gestion des Parkings"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (windowGestionParking), notebook1);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  labelNumeroPJ = gtk_label_new (_("Numero Parking "));
  gtk_widget_show (labelNumeroPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelNumeroPJ, 8, 40);
  gtk_widget_set_size_request (labelNumeroPJ, 112, 40);

  spinNumeroPJ_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  spinNumeroPJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinNumeroPJ_adj), 1, 0);
  gtk_widget_show (spinNumeroPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), spinNumeroPJ, 152, 48);
  gtk_widget_set_size_request (spinNumeroPJ, 184, 27);

  labelDatePJ = gtk_label_new (_("Date Construction"));
  gtk_widget_show (labelDatePJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelDatePJ, 0, 104);
  gtk_widget_set_size_request (labelDatePJ, 136, 33);

  spinJourPJ_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinJourPJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourPJ_adj), 1, 0);
  gtk_widget_show (spinJourPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), spinJourPJ, 152, 104);
  gtk_widget_set_size_request (spinJourPJ, 48, 27);

  spinMoisPJ_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinMoisPJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisPJ_adj), 1, 0);
  gtk_widget_show (spinMoisPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), spinMoisPJ, 200, 104);
  gtk_widget_set_size_request (spinMoisPJ, 48, 27);

  spinAnneePJ_adj = gtk_adjustment_new (1, 2024, 2060, 1, 10, 10);
  spinAnneePJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneePJ_adj), 1, 0);
  gtk_widget_show (spinAnneePJ);
  gtk_fixed_put (GTK_FIXED (fixed8), spinAnneePJ, 248, 104);
  gtk_widget_set_size_request (spinAnneePJ, 80, 27);

  labelAnneePJ = gtk_label_new (_("Capacite Parking"));
  gtk_widget_show (labelAnneePJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelAnneePJ, 8, 168);
  gtk_widget_set_size_request (labelAnneePJ, 120, 33);

  spinCapacitePJ_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinCapacitePJ = gtk_spin_button_new (GTK_ADJUSTMENT (spinCapacitePJ_adj), 1, 0);
  gtk_widget_show (spinCapacitePJ);
  gtk_fixed_put (GTK_FIXED (fixed8), spinCapacitePJ, 160, 168);
  gtk_widget_set_size_request (spinCapacitePJ, 176, 27);

  entryNomPJ = gtk_entry_new ();
  gtk_widget_show (entryNomPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), entryNomPJ, 528, 48);
  gtk_widget_set_size_request (entryNomPJ, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomPJ), 8226);

  labelAdressePJ = gtk_label_new (_("Adresse Parking"));
  gtk_widget_show (labelAdressePJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelAdressePJ, 384, 104);
  gtk_widget_set_size_request (labelAdressePJ, 120, 33);

  entryAdressePJ = gtk_entry_new ();
  gtk_widget_show (entryAdressePJ);
  gtk_fixed_put (GTK_FIXED (fixed8), entryAdressePJ, 528, 104);
  gtk_widget_set_size_request (entryAdressePJ, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAdressePJ), 8226);

  entryPrixPJ = gtk_entry_new ();
  gtk_widget_show (entryPrixPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), entryPrixPJ, 528, 160);
  gtk_widget_set_size_request (entryPrixPJ, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrixPJ), 8226);

  labelSecurite = gtk_label_new (_("Securite"));
  gtk_widget_show (labelSecurite);
  gtk_fixed_put (GTK_FIXED (fixed8), labelSecurite, 0, 240);
  gtk_widget_set_size_request (labelSecurite, 88, 25);

  labelNomPJ = gtk_label_new (_("Nom Parking "));
  gtk_widget_show (labelNomPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelNomPJ, 376, 40);
  gtk_widget_set_size_request (labelNomPJ, 120, 33);

  labelPrixPJ = gtk_label_new (_("Prix Parking "));
  gtk_widget_show (labelPrixPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelPrixPJ, 384, 160);
  gtk_widget_set_size_request (labelPrixPJ, 112, 33);

  labelSecteurPJ = gtk_label_new (_("Secteur"));
  gtk_widget_show (labelSecteurPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelSecteurPJ, 392, 232);
  gtk_widget_set_size_request (labelSecteurPJ, 80, 25);

  buttonAjouterParking = gtk_button_new ();
  gtk_widget_show (buttonAjouterParking);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonAjouterParking, 120, 344);
  gtk_widget_set_size_request (buttonAjouterParking, 152, 45);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonAjouterParking), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox2), label18, FALSE, FALSE, 0);

  checkSecuritePJ1 = gtk_check_button_new_with_mnemonic (_("camera"));
  gtk_widget_show (checkSecuritePJ1);
  gtk_fixed_put (GTK_FIXED (fixed8), checkSecuritePJ1, 160, 240);
  gtk_widget_set_size_request (checkSecuritePJ1, 118, 24);

  checkSecuritePJ2 = gtk_check_button_new_with_mnemonic (_("gardien"));
  gtk_widget_show (checkSecuritePJ2);
  gtk_fixed_put (GTK_FIXED (fixed8), checkSecuritePJ2, 160, 280);
  gtk_widget_set_size_request (checkSecuritePJ2, 118, 24);

  radioSecteurPJ1 = gtk_radio_button_new_with_mnemonic (NULL, _("Prive"));
  gtk_widget_show (radioSecteurPJ1);
  gtk_fixed_put (GTK_FIXED (fixed8), radioSecteurPJ1, 544, 232);
  gtk_widget_set_size_request (radioSecteurPJ1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioSecteurPJ1), radioSecteurPJ1_group);
  radioSecteurPJ1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioSecteurPJ1));

  radioSecteurPJ2 = gtk_radio_button_new_with_mnemonic (NULL, _("Publique"));
  gtk_widget_show (radioSecteurPJ2);
  gtk_fixed_put (GTK_FIXED (fixed8), radioSecteurPJ2, 544, 272);
  gtk_widget_set_size_request (radioSecteurPJ2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioSecteurPJ2), radioSecteurPJ1_group);
  radioSecteurPJ1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioSecteurPJ2));

  labelResultatPJ = gtk_label_new ("");
  gtk_widget_show (labelResultatPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), labelResultatPJ, 104, 392);
  gtk_widget_set_size_request (labelResultatPJ, 536, 224);

  buttonMenuPJ = gtk_button_new ();
  gtk_widget_show (buttonMenuPJ);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonMenuPJ, 320, 344);
  gtk_widget_set_size_request (buttonMenuPJ, 152, 48);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonMenuPJ), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image2 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox3), image2, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Menu"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox3), label19, FALSE, FALSE, 0);

  labelGAjouterParking = gtk_label_new (_("Ajouter Parking"));
  gtk_widget_show (labelGAjouterParking);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labelGAjouterParking);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  spinNumeroPM_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  spinNumeroPM = gtk_spin_button_new (GTK_ADJUSTMENT (spinNumeroPM_adj), 1, 0);
  gtk_widget_show (spinNumeroPM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinNumeroPM, 152, 48);
  gtk_widget_set_size_request (spinNumeroPM, 184, 27);

  spinJourPM_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinJourPM = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourPM_adj), 1, 0);
  gtk_widget_show (spinJourPM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinJourPM, 152, 104);
  gtk_widget_set_size_request (spinJourPM, 48, 27);

  spinMoisPM_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinMoisPM = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisPM_adj), 1, 0);
  gtk_widget_show (spinMoisPM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinMoisPM, 200, 104);
  gtk_widget_set_size_request (spinMoisPM, 48, 27);

  spinAnneePM_adj = gtk_adjustment_new (1, 2024, 2060, 1, 10, 10);
  spinAnneePM = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneePM_adj), 1, 0);
  gtk_widget_show (spinAnneePM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinAnneePM, 248, 104);
  gtk_widget_set_size_request (spinAnneePM, 80, 27);

  spinCapacitePM_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinCapacitePM = gtk_spin_button_new (GTK_ADJUSTMENT (spinCapacitePM_adj), 1, 0);
  gtk_widget_show (spinCapacitePM);
  gtk_fixed_put (GTK_FIXED (fixed9), spinCapacitePM, 160, 168);
  gtk_widget_set_size_request (spinCapacitePM, 176, 27);

  entryNomPM = gtk_entry_new ();
  gtk_widget_show (entryNomPM);
  gtk_fixed_put (GTK_FIXED (fixed9), entryNomPM, 528, 48);
  gtk_widget_set_size_request (entryNomPM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNomPM), 8226);

  entryAdressePM = gtk_entry_new ();
  gtk_widget_show (entryAdressePM);
  gtk_fixed_put (GTK_FIXED (fixed9), entryAdressePM, 528, 104);
  gtk_widget_set_size_request (entryAdressePM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryAdressePM), 8226);

  entryPrixPM = gtk_entry_new ();
  gtk_widget_show (entryPrixPM);
  gtk_fixed_put (GTK_FIXED (fixed9), entryPrixPM, 528, 160);
  gtk_widget_set_size_request (entryPrixPM, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPrixPM), 8226);

  labelNomPM = gtk_label_new (_("Nom Parking "));
  gtk_widget_show (labelNomPM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelNomPM, 376, 40);
  gtk_widget_set_size_request (labelNomPM, 120, 33);

  labelDatePM = gtk_label_new (_("Date Construction"));
  gtk_widget_show (labelDatePM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelDatePM, 0, 104);
  gtk_widget_set_size_request (labelDatePM, 136, 33);

  labelAdressePM = gtk_label_new (_("Adresse Parking"));
  gtk_widget_show (labelAdressePM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelAdressePM, 384, 104);
  gtk_widget_set_size_request (labelAdressePM, 120, 33);

  labelPrixPM = gtk_label_new (_("Prix Parking "));
  gtk_widget_show (labelPrixPM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelPrixPM, 384, 160);
  gtk_widget_set_size_request (labelPrixPM, 112, 33);

  labelCapacitePM = gtk_label_new (_("Capacite Parking"));
  gtk_widget_show (labelCapacitePM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelCapacitePM, 8, 168);
  gtk_widget_set_size_request (labelCapacitePM, 120, 33);

  labelSecuritePM = gtk_label_new (_("Securite"));
  gtk_widget_show (labelSecuritePM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelSecuritePM, 0, 240);
  gtk_widget_set_size_request (labelSecuritePM, 88, 25);

  labelSecteurPM = gtk_label_new (_("Secteur"));
  gtk_widget_show (labelSecteurPM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelSecteurPM, 392, 232);
  gtk_widget_set_size_request (labelSecteurPM, 80, 25);

  buttonModifierParking = gtk_button_new ();
  gtk_widget_show (buttonModifierParking);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonModifierParking, 256, 352);
  gtk_widget_set_size_request (buttonModifierParking, 152, 45);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonModifierParking), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox6), image5, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox6), label31, FALSE, FALSE, 0);

  buttonRecupererPM = gtk_button_new ();
  gtk_widget_show (buttonRecupererPM);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonRecupererPM, 80, 352);
  gtk_widget_set_size_request (buttonRecupererPM, 138, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonRecupererPM), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image6 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox7), image6, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Recuperer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox7), label32, FALSE, FALSE, 0);

  checkSecuritePM1 = gtk_check_button_new_with_mnemonic (_("camera"));
  gtk_widget_show (checkSecuritePM1);
  gtk_fixed_put (GTK_FIXED (fixed9), checkSecuritePM1, 160, 240);
  gtk_widget_set_size_request (checkSecuritePM1, 118, 24);

  checkSecuritePM2 = gtk_check_button_new_with_mnemonic (_("gardien"));
  gtk_widget_show (checkSecuritePM2);
  gtk_fixed_put (GTK_FIXED (fixed9), checkSecuritePM2, 160, 280);
  gtk_widget_set_size_request (checkSecuritePM2, 118, 24);

  radioSecteurPM1 = gtk_radio_button_new_with_mnemonic (NULL, _("Prive"));
  gtk_widget_show (radioSecteurPM1);
  gtk_fixed_put (GTK_FIXED (fixed9), radioSecteurPM1, 544, 232);
  gtk_widget_set_size_request (radioSecteurPM1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioSecteurPM1), radioSecteurPM1_group);
  radioSecteurPM1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioSecteurPM1));

  radioSecteurPM2 = gtk_radio_button_new_with_mnemonic (NULL, _("Publique"));
  gtk_widget_show (radioSecteurPM2);
  gtk_fixed_put (GTK_FIXED (fixed9), radioSecteurPM2, 544, 272);
  gtk_widget_set_size_request (radioSecteurPM2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioSecteurPM2), radioSecteurPM1_group);
  radioSecteurPM1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioSecteurPM2));

  labelResultatPM = gtk_label_new ("");
  gtk_widget_show (labelResultatPM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelResultatPM, 96, 408);
  gtk_widget_set_size_request (labelResultatPM, 544, 208);

  buttonMenuPM = gtk_button_new ();
  gtk_widget_show (buttonMenuPM);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonMenuPM, 440, 352);
  gtk_widget_set_size_request (buttonMenuPM, 152, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonMenuPM), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image4 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox5), image4, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Menu"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox5), label30, FALSE, FALSE, 0);

  labelNumeroPM = gtk_label_new (_("Numero Parking "));
  gtk_widget_show (labelNumeroPM);
  gtk_fixed_put (GTK_FIXED (fixed9), labelNumeroPM, 8, 40);
  gtk_widget_set_size_request (labelNumeroPM, 112, 40);

  labelGModifierParking = gtk_label_new (_("Modifier Parking"));
  gtk_widget_show (labelGModifierParking);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), labelGModifierParking);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview1, 64, 136);
  gtk_widget_set_size_request (treeview1, 784, 344);

  buttonMenuPCH = gtk_button_new ();
  gtk_widget_show (buttonMenuPCH);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonMenuPCH, 304, 480);
  gtk_widget_set_size_request (buttonMenuPCH, 144, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonMenuPCH), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image10 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox11), image10, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Menu"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  buttonParkingTrier = gtk_button_new ();
  gtk_widget_show (buttonParkingTrier);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonParkingTrier, 544, 32);
  gtk_widget_set_size_request (buttonParkingTrier, 192, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonParkingTrier), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image9 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox10), image9, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Parking Trier"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  buttonParkingAvecAgent = gtk_button_new ();
  gtk_widget_show (buttonParkingAvecAgent);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonParkingAvecAgent, 32, 32);
  gtk_widget_set_size_request (buttonParkingAvecAgent, 208, 45);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonParkingAvecAgent), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image7 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox8), image7, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Parking Avec Agent"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox8), label33, FALSE, FALSE, 0);

  buttonParkingSansAgent = gtk_button_new ();
  gtk_widget_show (buttonParkingSansAgent);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonParkingSansAgent, 288, 32);
  gtk_widget_set_size_request (buttonParkingSansAgent, 216, 45);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonParkingSansAgent), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image8 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox9), image8, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Parking Sans Agent"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox9), label34, FALSE, FALSE, 0);

  labelGChercherParking = gtk_label_new (_("Chercher Parking"));
  gtk_widget_show (labelGChercherParking);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), labelGChercherParking);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  labelParkingPS = gtk_label_new (_("Liste des parkings :"));
  gtk_widget_show (labelParkingPS);
  gtk_fixed_put (GTK_FIXED (fixed7), labelParkingPS, 88, 48);
  gtk_widget_set_size_request (labelParkingPS, 176, 49);

  labelResultatSP = gtk_label_new ("");
  gtk_widget_show (labelResultatSP);
  gtk_fixed_put (GTK_FIXED (fixed7), labelResultatSP, 240, 256);
  gtk_widget_set_size_request (labelResultatSP, 368, 96);

  comboboxParkingPS = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxParkingPS);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxParkingPS, 264, 48);
  gtk_widget_set_size_request (comboboxParkingPS, 232, 55);

  buttonActualiserLPS = gtk_button_new ();
  gtk_widget_show (buttonActualiserLPS);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonActualiserLPS, 520, 48);
  gtk_widget_set_size_request (buttonActualiserLPS, 152, 53);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonActualiserLPS), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image11 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox12), image11, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox12), label42, FALSE, FALSE, 0);

  buttonSupprimerPS = gtk_button_new ();
  gtk_widget_show (buttonSupprimerPS);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonSupprimerPS, 312, 144);
  gtk_widget_set_size_request (buttonSupprimerPS, 154, 56);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonSupprimerPS), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox13), image12, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox13), label43, FALSE, FALSE, 0);

  labelGSupprimerParking = gtk_label_new (_("Supprimer Parking"));
  gtk_widget_show (labelGSupprimerParking);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), labelGSupprimerParking);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 240, 16);
  gtk_widget_set_size_request (treeview2, 328, 280);

  labelParkingLAffAg = gtk_label_new (_("Liste Parkings :"));
  gtk_widget_show (labelParkingLAffAg);
  gtk_fixed_put (GTK_FIXED (fixed4), labelParkingLAffAg, 168, 336);
  gtk_widget_set_size_request (labelParkingLAffAg, 120, 25);

  labelAgentLAffAg = gtk_label_new (_("Liste Agents :"));
  gtk_widget_show (labelAgentLAffAg);
  gtk_fixed_put (GTK_FIXED (fixed4), labelAgentLAffAg, 168, 384);
  gtk_widget_set_size_request (labelAgentLAffAg, 104, 25);

  comboboxParkingLAffAg = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxParkingLAffAg);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxParkingLAffAg, 296, 328);
  gtk_widget_set_size_request (comboboxParkingLAffAg, 200, 39);

  comboboxAgentLAffAg = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxAgentLAffAg);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxAgentLAffAg, 296, 376);
  gtk_widget_set_size_request (comboboxAgentLAffAg, 200, 40);

  labelResultatAffAg = gtk_label_new ("");
  gtk_widget_show (labelResultatAffAg);
  gtk_fixed_put (GTK_FIXED (fixed4), labelResultatAffAg, 208, 496);
  gtk_widget_set_size_request (labelResultatAffAg, 440, 96);

  buttonActualiserAffAg = gtk_button_new ();
  gtk_widget_show (buttonActualiserAffAg);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonActualiserAffAg, 528, 336);
  gtk_widget_set_size_request (buttonActualiserAffAg, 144, 53);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonActualiserAffAg), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image13 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox14), image13, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  buttonAffecterAgent = gtk_button_new ();
  gtk_widget_show (buttonAffecterAgent);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonAffecterAgent, 328, 432);
  gtk_widget_set_size_request (buttonAffecterAgent, 160, 53);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonAffecterAgent), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox15), image14, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox15), label45, FALSE, FALSE, 0);

  labelGAffecterAgent = gtk_label_new (_("Affecter Agent"));
  gtk_widget_show (labelGAffecterAgent);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), labelGAffecterAgent);

  g_signal_connect ((gpointer) buttonAjouterParking, "clicked",
                    G_CALLBACK (on_buttonAjouterParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonMenuPJ, "clicked",
                    G_CALLBACK (on_buttonMenuPJ_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierParking, "clicked",
                    G_CALLBACK (on_buttonModifierParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRecupererPM, "clicked",
                    G_CALLBACK (on_buttonRecupererPM_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonMenuPM, "clicked",
                    G_CALLBACK (on_buttonMenuPM_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonMenuPCH, "clicked",
                    G_CALLBACK (on_buttonMenuPCH_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonParkingTrier, "clicked",
                    G_CALLBACK (on_buttonParkingTrier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonParkingAvecAgent, "clicked",
                    G_CALLBACK (on_buttonParkingAvecAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonParkingSansAgent, "clicked",
                    G_CALLBACK (on_buttonParkingSansAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonActualiserLPS, "clicked",
                    G_CALLBACK (on_buttonActualiserLPS_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimerPS, "clicked",
                    G_CALLBACK (on_buttonSupprimerPS_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonActualiserAffAg, "clicked",
                    G_CALLBACK (on_buttonActualiserAffAg_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAffecterAgent, "clicked",
                    G_CALLBACK (on_buttonAffecterAgent_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionParking, windowGestionParking, "windowGestionParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelNumeroPJ, "labelNumeroPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinNumeroPJ, "spinNumeroPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelDatePJ, "labelDatePJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinJourPJ, "spinJourPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinMoisPJ, "spinMoisPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinAnneePJ, "spinAnneePJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelAnneePJ, "labelAnneePJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinCapacitePJ, "spinCapacitePJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, entryNomPJ, "entryNomPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelAdressePJ, "labelAdressePJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, entryAdressePJ, "entryAdressePJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, entryPrixPJ, "entryPrixPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelSecurite, "labelSecurite");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelNomPJ, "labelNomPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelPrixPJ, "labelPrixPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelSecteurPJ, "labelSecteurPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonAjouterParking, "buttonAjouterParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label18, "label18");
  GLADE_HOOKUP_OBJECT (windowGestionParking, checkSecuritePJ1, "checkSecuritePJ1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, checkSecuritePJ2, "checkSecuritePJ2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, radioSecteurPJ1, "radioSecteurPJ1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, radioSecteurPJ2, "radioSecteurPJ2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelResultatPJ, "labelResultatPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonMenuPJ, "buttonMenuPJ");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelGAjouterParking, "labelGAjouterParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinNumeroPM, "spinNumeroPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinJourPM, "spinJourPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinMoisPM, "spinMoisPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinAnneePM, "spinAnneePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, spinCapacitePM, "spinCapacitePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, entryNomPM, "entryNomPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, entryAdressePM, "entryAdressePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, entryPrixPM, "entryPrixPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelNomPM, "labelNomPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelDatePM, "labelDatePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelAdressePM, "labelAdressePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelPrixPM, "labelPrixPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelCapacitePM, "labelCapacitePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelSecuritePM, "labelSecuritePM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelSecteurPM, "labelSecteurPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonModifierParking, "buttonModifierParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonRecupererPM, "buttonRecupererPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label32, "label32");
  GLADE_HOOKUP_OBJECT (windowGestionParking, checkSecuritePM1, "checkSecuritePM1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, checkSecuritePM2, "checkSecuritePM2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, radioSecteurPM1, "radioSecteurPM1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, radioSecteurPM2, "radioSecteurPM2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelResultatPM, "labelResultatPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonMenuPM, "buttonMenuPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelNumeroPM, "labelNumeroPM");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelGModifierParking, "labelGModifierParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowGestionParking, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonMenuPCH, "buttonMenuPCH");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonParkingTrier, "buttonParkingTrier");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonParkingAvecAgent, "buttonParkingAvecAgent");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label33, "label33");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonParkingSansAgent, "buttonParkingSansAgent");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelGChercherParking, "labelGChercherParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelParkingPS, "labelParkingPS");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelResultatSP, "labelResultatSP");
  GLADE_HOOKUP_OBJECT (windowGestionParking, comboboxParkingPS, "comboboxParkingPS");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonActualiserLPS, "buttonActualiserLPS");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label42, "label42");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonSupprimerPS, "buttonSupprimerPS");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelGSupprimerParking, "labelGSupprimerParking");
  GLADE_HOOKUP_OBJECT (windowGestionParking, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowGestionParking, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelParkingLAffAg, "labelParkingLAffAg");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelAgentLAffAg, "labelAgentLAffAg");
  GLADE_HOOKUP_OBJECT (windowGestionParking, comboboxParkingLAffAg, "comboboxParkingLAffAg");
  GLADE_HOOKUP_OBJECT (windowGestionParking, comboboxAgentLAffAg, "comboboxAgentLAffAg");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelResultatAffAg, "labelResultatAffAg");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonActualiserAffAg, "buttonActualiserAffAg");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowGestionParking, buttonAffecterAgent, "buttonAffecterAgent");
  GLADE_HOOKUP_OBJECT (windowGestionParking, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowGestionParking, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowGestionParking, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowGestionParking, label45, "label45");
  GLADE_HOOKUP_OBJECT (windowGestionParking, labelGAffecterAgent, "labelGAffecterAgent");

  return windowGestionParking;
}

GtkWidget*
create_windowGestionReservation (void)
{
  GtkWidget *windowGestionReservation;

  windowGestionReservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionReservation), _("Gestion des Reservations"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionReservation, windowGestionReservation, "windowGestionReservation");

  return windowGestionReservation;
}

GtkWidget*
create_windowGestionCitoyen (void)
{
  GtkWidget *windowGestionCitoyen;

  windowGestionCitoyen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionCitoyen), _("Gestion des Citoyens"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionCitoyen, windowGestionCitoyen, "windowGestionCitoyen");

  return windowGestionCitoyen;
}

GtkWidget*
create_windowGestionService (void)
{
  GtkWidget *windowGestionService;

  windowGestionService = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionService), _("Gestion des Services"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionService, windowGestionService, "windowGestionService");

  return windowGestionService;
}

GtkWidget*
create_windowGestionAgent (void)
{
  GtkWidget *windowGestionAgent;

  windowGestionAgent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionAgent), _("Gestion des Agents"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionAgent, windowGestionAgent, "windowGestionAgent");

  return windowGestionAgent;
}

GtkWidget*
create_windowGestionReclamation (void)
{
  GtkWidget *windowGestionReclamation;

  windowGestionReclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowGestionReclamation), _("Gestion des Reclamations"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowGestionReclamation, windowGestionReclamation, "windowGestionReclamation");

  return windowGestionReclamation;
}

