/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Athentification (void);
GtkWidget* create_espace_d_admininstration (void);
GtkWidget* create_espace_citoyen (void);
GtkWidget* create_Agent (void);
GtkWidget* create_Ajouterunservice (void);
GtkWidget* create_Citoyen (void);
GtkWidget* create_reservation (void);
GtkWidget* create_reclamation (void);
GtkWidget* create_Modifierunservice (void);
GtkWidget* create_Consulterunservice (void);
GtkWidget* create_Supprimerunservice (void);
GtkWidget* create_stationnement (void);
GtkWidget* create_Calculer_Facture (void);
GtkWidget* create_gestionParkings (void);
GtkWidget* create_window1 (void);
