/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Athentification;
  GtkWidget *espace_d_admininstration;
  GtkWidget *espace_citoyen;
  GtkWidget *Parking;
  GtkWidget *Agent;
  GtkWidget *ajouterunservice;
 GtkWidget *modifierunservice;
 GtkWidget *supprimerunservice;
 GtkWidget *consulterunservice;
  GtkWidget *Citoyen;
  GtkWidget *reservation;
  GtkWidget *reclamation;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Athentification = create_Athentification ();
  gtk_widget_show (Athentification);
  espace_d_admininstration = create_espace_d_admininstration ();
  gtk_widget_show (espace_d_admininstration);
  espace_citoyen = create_espace_citoyen ();
  gtk_widget_show (espace_citoyen);
  //Parking = create_Parking ();
  //gtk_widget_show (Parking);
ajouterunservice = create_Ajouterunservice ();
  gtk_widget_show (ajouterunservice);
modifierunservice = create_Modifierunservice ();
  gtk_widget_show (modifierunservice);
supprimerunservice = create_Supprimerunservice ();
  gtk_widget_show (supprimerunservice);
consulterunservice = create_Consulterunservice ();
  gtk_widget_show (consulterunservice);
  Agent = create_Agent ();
  gtk_widget_show (Agent);
  Citoyen = create_Citoyen ();
  gtk_widget_show (Citoyen);
  reservation = create_reservation ();
  gtk_widget_show (reservation);
  reclamation = create_reclamation ();
  gtk_widget_show (reclamation);

  gtk_main ();
  return 0;
}

