/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowLogin;
  GtkWidget *windowInscription;
  GtkWidget *windowMenu;
  GtkWidget *windowGestionParking;
  GtkWidget *windowGestionReservation;
  GtkWidget *windowGestionCitoyen;
  GtkWidget *windowGestionService;
  GtkWidget *windowGestionAgent;
  GtkWidget *windowGestionReclamation;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  windowLogin = create_windowLogin ();
  gtk_widget_show (windowLogin);
  /*windowInscription = create_windowInscription ();
  gtk_widget_show (windowInscription);
  windowMenu = create_windowMenu ();
  gtk_widget_show (windowMenu);
  windowGestionParking = create_windowGestionParking ();
  gtk_widget_show (windowGestionParking);
  windowGestionReservation = create_windowGestionReservation ();
  gtk_widget_show (windowGestionReservation);
  windowGestionCitoyen = create_windowGestionCitoyen ();
  gtk_widget_show (windowGestionCitoyen);
  windowGestionService = create_windowGestionService ();
  gtk_widget_show (windowGestionService);
  windowGestionAgent = create_windowGestionAgent ();
  gtk_widget_show (windowGestionAgent);
  windowGestionReclamation = create_windowGestionReclamation ();
  gtk_widget_show (windowGestionReclamation);*/

  gtk_main ();
  return 0;
}

