/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowLogin (void);
GtkWidget* create_windowInscription (void);
GtkWidget* create_windowMenu (void);
GtkWidget* create_windowGestionParking (void);
GtkWidget* create_windowGestionReservation (void);
GtkWidget* create_windowGestionCitoyen (void);
GtkWidget* create_windowGestionAgent (void);
GtkWidget* create_windowGestionReclamation (void);
GtkWidget* create_windowGestionService (void);
GtkWidget* create_Supprimer (void);
